# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - name: redis:latest
#    alias: redis-adduser

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/


stages:
- install_libs
- lint
- test
- release

install_libs:
  stage: install_libs
  script:
    - npm install

lint:
  stage: lint
  script:
    - node_modules/eslint/bin/eslint.js routes/*.js app.js

test:
  stage: test
  script:
    - export CASSANDRA_HOST="aglagla"
    - export CASSANDRA_PORT="obloblo"
    - export CASSANDRA_DATACENTER="kek"
    - export CASSANDRA_CRYPTO_DATA_KEYSPACE="jej"
    - export TEST_MODE="true"
    - export REPORT_SERVICE_URL="none"
    - node app.js &
    - sleep 2 && npm test

release:
  image: node:13
  stage: release
  only:
    refs:
    - master
    - alpha
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  script:
    - npm install @semantic-release/gitlab
    - npx semantic-release
